-- ============================================================================
-- ReadFlow — Digital Reading & Knowledge Platform
-- PostgreSQL Production Schema
-- Version: 1.0
-- ============================================================================
-- Conventions:
--   - PK: UUID (uuid-ossp), generated by DB (uuid_generate_v4()) or app layer.
--   - Timestamps: TIMESTAMPTZ (always store in UTC, let app layer localize).
--   - Enum-like fields: VARCHAR + CHECK constraint (easier to evolve than
--     native PG ENUM, no ALTER TYPE headaches in CI/CD pipelines).
--   - Soft delete: deleted_at TIMESTAMPTZ NULL on domain-owned, user-facing
--     entities (books, documents, annotations, blogs...) so data can be
--     recovered / audited. Hard delete only for join/log tables.
--   - Every FK has a matching index (Postgres does NOT auto-index FKs).
--   - updated_at is maintained by trigger, not by the application.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 0. EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";   -- uuid_generate_v4()
CREATE EXTENSION IF NOT EXISTS "citext";      -- case-insensitive email/username
CREATE EXTENSION IF NOT EXISTS "pg_trgm";     -- fuzzy/full-text search (title, author...)

-- ============================================================================
-- 0.1 COMMON — trigger function for updated_at
-- ============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 1. USER DOMAIN
-- ============================================================================

CREATE TABLE users (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- ID của user trong Keycloak
    keycloak_user_id    VARCHAR(255) NOT NULL UNIQUE,

    email               CITEXT NOT NULL UNIQUE,
    username            CITEXT NOT NULL UNIQUE,

    full_name           VARCHAR(255),
    avatar_url          TEXT,

    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED')),

    last_login_at       TIMESTAMPTZ,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    deleted_at          TIMESTAMPTZ
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_users_status
ON users(status)
WHERE deleted_at IS NULL;

CREATE INDEX idx_users_keycloak_user_id
ON users(keycloak_user_id);

CREATE TABLE user_preferences (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    user_id         UUID NOT NULL UNIQUE
                    REFERENCES users(id)
                    ON DELETE CASCADE,

    theme           VARCHAR(20) NOT NULL DEFAULT 'SYSTEM'
                    CHECK (theme IN ('LIGHT', 'DARK', 'SYSTEM')),

    font_size       SMALLINT NOT NULL DEFAULT 16
                    CHECK (font_size BETWEEN 8 AND 48),

    language        VARCHAR(10) NOT NULL DEFAULT 'en',

    reading_mode    VARCHAR(20) NOT NULL DEFAULT 'SINGLE_PAGE'
                    CHECK (reading_mode IN ('SINGLE_PAGE', 'TWO_PAGE')),

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_user_preferences_updated_at
BEFORE UPDATE ON user_preferences
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- 2. BOOK DOMAIN
-- ============================================================================

CREATE TABLE publishers (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE authors (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(255) NOT NULL,
    bio         TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_authors_name_trgm ON authors USING gin (name gin_trgm_ops);

-- Self-referencing so categories can be hierarchical (e.g. Fiction > Sci-Fi).
CREATE TABLE categories (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    parent_id   UUID REFERENCES categories(id) ON DELETE SET NULL,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_categories_parent_id ON categories(parent_id);

CREATE TABLE books (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title           VARCHAR(500) NOT NULL,
    subtitle        VARCHAR(500),
    description     TEXT,
    cover_url       TEXT,
    isbn            VARCHAR(20) UNIQUE,
    language        VARCHAR(10) NOT NULL DEFAULT 'en',
    publisher_id    UUID REFERENCES publishers(id) ON DELETE SET NULL,
    published_date  DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                    CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);
CREATE TRIGGER trg_books_updated_at BEFORE UPDATE ON books
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_books_publisher_id ON books(publisher_id);
CREATE INDEX idx_books_status ON books(status) WHERE deleted_at IS NULL;
CREATE INDEX idx_books_title_trgm ON books USING gin (title gin_trgm_ops);

-- Many-to-many: a book can have multiple authors, an author multiple books.
CREATE TABLE book_authors (
    book_id     UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    author_id   UUID NOT NULL REFERENCES authors(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);
CREATE INDEX idx_book_authors_author_id ON book_authors(author_id);

CREATE TABLE book_categories (
    book_id     UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, category_id)
);
CREATE INDEX idx_book_categories_category_id ON book_categories(category_id);

CREATE TABLE reviews (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    book_id     UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (book_id, user_id)  -- one review per user per book
);
CREATE TRIGGER trg_reviews_updated_at BEFORE UPDATE ON reviews
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_reviews_book_id ON reviews(book_id);
CREATE INDEX idx_reviews_user_id ON reviews(user_id);

CREATE TABLE favorites (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id     UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, book_id)
);
CREATE INDEX idx_favorites_book_id ON favorites(book_id);

-- ============================================================================
-- 3. DOCUMENT DOMAIN — the actual readable content behind a Book
-- ============================================================================

CREATE TABLE documents (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    book_id             UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    uploaded_by         UUID REFERENCES users(id) ON DELETE SET NULL,
    original_filename   VARCHAR(500) NOT NULL,
    file_url            TEXT NOT NULL,
    file_type           VARCHAR(20) NOT NULL
                        CHECK (file_type IN ('PDF', 'EPUB', 'TXT')),
    file_size_bytes     BIGINT NOT NULL CHECK (file_size_bytes >= 0),
    processing_status   VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (processing_status IN
                            ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    processing_error    TEXT,
    total_chapters      INT NOT NULL DEFAULT 0,
    total_pages         INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON documents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_documents_book_id ON documents(book_id);
CREATE INDEX idx_documents_uploaded_by ON documents(uploaded_by);
CREATE INDEX idx_documents_processing_status ON documents(processing_status)
    WHERE processing_status IN ('PENDING', 'PROCESSING');

CREATE TABLE chapters (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_number  INT NOT NULL,
    title           VARCHAR(500),
    start_page      INT,
    end_page        INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, chapter_number)
);
CREATE INDEX idx_chapters_document_id ON chapters(document_id);

-- pages.content can be large; consider TOAST-friendly TEXT (default) and
-- avoid loading full document rows when only metadata is needed.
CREATE TABLE pages (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_id      UUID REFERENCES chapters(id) ON DELETE SET NULL,
    page_number     INT NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, page_number)
);
CREATE INDEX idx_pages_document_id ON pages(document_id);
CREATE INDEX idx_pages_chapter_id ON pages(chapter_id);

-- ============================================================================
-- 4. READER DOMAIN — reading experience & progress
-- ============================================================================

CREATE TABLE reading_progress (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id         UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    current_page_id     UUID REFERENCES pages(id) ON DELETE SET NULL,
    current_chapter_id  UUID REFERENCES chapters(id) ON DELETE SET NULL,
    progress_percent    NUMERIC(5,2) NOT NULL DEFAULT 0
                        CHECK (progress_percent BETWEEN 0 AND 100),
    reading_status      VARCHAR(20) NOT NULL DEFAULT 'WANT_TO_READ'
                        CHECK (reading_status IN
                            ('WANT_TO_READ', 'READING', 'COMPLETED', 'PAUSED')),
    last_read_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, document_id)
);
CREATE TRIGGER trg_reading_progress_updated_at BEFORE UPDATE ON reading_progress
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_reading_progress_document_id ON reading_progress(document_id);
CREATE INDEX idx_reading_progress_user_status ON reading_progress(user_id, reading_status);

-- Session-level history, used for "Continue Reading" and reading-time stats.
CREATE TABLE reading_sessions (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id         UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    page_id             UUID REFERENCES pages(id) ON DELETE SET NULL,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at            TIMESTAMPTZ,
    duration_seconds    INT CHECK (duration_seconds >= 0)
);
CREATE INDEX idx_reading_sessions_user_id ON reading_sessions(user_id, started_at DESC);
CREATE INDEX idx_reading_sessions_document_id ON reading_sessions(document_id);

-- ============================================================================
-- 5. ANNOTATION DOMAIN — highlight / note / bookmark / tag
-- ============================================================================

CREATE TABLE annotations (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    page_id         UUID NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
    type            VARCHAR(20) NOT NULL
                    CHECK (type IN ('HIGHLIGHT', 'NOTE', 'BOOKMARK')),
    selected_text   TEXT,               -- the highlighted excerpt, if any
    note_content    TEXT,               -- free-text note, if any
    color           VARCHAR(20) NOT NULL DEFAULT 'YELLOW'
                    CHECK (color IN ('YELLOW', 'GREEN', 'BLUE', 'PINK', 'PURPLE')),
    position_start  INT,                -- character offset within page content
    position_end    INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CHECK (position_end IS NULL OR position_start IS NULL OR position_end >= position_start)
);
CREATE TRIGGER trg_annotations_updated_at BEFORE UPDATE ON annotations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_annotations_document_id ON annotations(document_id);
CREATE INDEX idx_annotations_page_id ON annotations(page_id);
CREATE INDEX idx_annotations_user_type ON annotations(user_id, type) WHERE deleted_at IS NULL;

-- Tags are user-scoped (each user builds their own tag vocabulary).
CREATE TABLE tags (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        VARCHAR(100) NOT NULL,
    color       VARCHAR(20),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

CREATE TABLE annotation_tags (
    annotation_id   UUID NOT NULL REFERENCES annotations(id) ON DELETE CASCADE,
    tag_id          UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (annotation_id, tag_id)
);
CREATE INDEX idx_annotation_tags_tag_id ON annotation_tags(tag_id);

-- ============================================================================
-- 6. LIBRARY DOMAIN — user's personal book shelf
-- ============================================================================
-- NOTE: kept separate from `favorites` per the product spec (Phase 1 keeps
-- favorite standalone; can be merged into library_items later if favorite
-- becomes just another status/flag on this table).

CREATE TABLE library_items (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id     UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL DEFAULT 'WANT_TO_READ'
                CHECK (status IN
                    ('WANT_TO_READ', 'READING', 'COMPLETED', 'ON_HOLD', 'DROPPED')),
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, book_id)
);
CREATE TRIGGER trg_library_items_updated_at BEFORE UPDATE ON library_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_library_items_user_status ON library_items(user_id, status);
CREATE INDEX idx_library_items_book_id ON library_items(book_id);

-- ============================================================================
-- 7. BLOG / COMMUNITY DOMAIN
-- ============================================================================

CREATE TABLE blogs (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           VARCHAR(500) NOT NULL,
    slug            VARCHAR(500) NOT NULL UNIQUE,
    content         TEXT NOT NULL,
    cover_url       TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                    CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);
CREATE TRIGGER trg_blogs_updated_at BEFORE UPDATE ON blogs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_blogs_user_id ON blogs(user_id);
CREATE INDEX idx_blogs_status_published ON blogs(status, published_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE blog_comments (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    blog_id             UUID NOT NULL REFERENCES blogs(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_comment_id   UUID REFERENCES blog_comments(id) ON DELETE CASCADE,
    content             TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);
CREATE TRIGGER trg_blog_comments_updated_at BEFORE UPDATE ON blog_comments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_blog_comments_blog_id ON blog_comments(blog_id);
CREATE INDEX idx_blog_comments_parent_id ON blog_comments(parent_comment_id);

CREATE TABLE blog_likes (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    blog_id     UUID NOT NULL REFERENCES blogs(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (blog_id, user_id)
);
CREATE INDEX idx_blog_likes_user_id ON blog_likes(user_id);

-- ============================================================================
-- 8. SUBSCRIPTION DOMAIN
-- ============================================================================

CREATE TABLE subscription_plans (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code                VARCHAR(20) NOT NULL UNIQUE
                        CHECK (code IN ('FREE', 'PRO')),
    name                VARCHAR(100) NOT NULL,
    price_cents         INT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
    currency            CHAR(3) NOT NULL DEFAULT 'USD',
    billing_interval    VARCHAR(20) NOT NULL DEFAULT 'MONTHLY'
                        CHECK (billing_interval IN ('MONTHLY', 'YEARLY', 'LIFETIME')),
    features            JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active           BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_subscriptions (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id             UUID NOT NULL REFERENCES subscription_plans(id),
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'CANCELED', 'EXPIRED', 'PAST_DUE')),
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_period_end  TIMESTAMPTZ,
    canceled_at         TIMESTAMPTZ,
    payment_provider    VARCHAR(50),      -- e.g. 'STRIPE', 'PAYPAL'
    payment_reference   VARCHAR(255),     -- external subscription/customer id
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_user_subscriptions_updated_at BEFORE UPDATE ON user_subscriptions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_user_subscriptions_plan_id ON user_subscriptions(plan_id);
-- Only one ACTIVE subscription per user at a time.
CREATE UNIQUE INDEX uq_user_subscriptions_active_per_user
    ON user_subscriptions(user_id) WHERE status = 'ACTIVE';

-- ============================================================================
-- 9. AI DOMAIN
-- ============================================================================

CREATE TABLE ai_chat_sessions (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id     UUID REFERENCES documents(id) ON DELETE CASCADE,
    book_id         UUID REFERENCES books(id) ON DELETE CASCADE,
    title           VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_ai_chat_sessions_updated_at BEFORE UPDATE ON ai_chat_sessions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_ai_chat_sessions_user_id ON ai_chat_sessions(user_id, updated_at DESC);
CREATE INDEX idx_ai_chat_sessions_document_id ON ai_chat_sessions(document_id);

CREATE TABLE ai_chat_messages (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id      UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    role            VARCHAR(20) NOT NULL CHECK (role IN ('USER', 'ASSISTANT')),
    content         TEXT NOT NULL,
    tokens_used     INT CHECK (tokens_used >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_chat_messages_session_id ON ai_chat_messages(session_id, created_at);

CREATE TABLE ai_summaries (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    scope           VARCHAR(20) NOT NULL
                    CHECK (scope IN ('PAGE', 'SECTION', 'CHAPTER', 'BOOK')),
    scope_ref_id    UUID,   -- points to pages.id or chapters.id depending on scope
    content         TEXT NOT NULL,
    model_used      VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_summaries_document_id ON ai_summaries(document_id);
CREATE INDEX idx_ai_summaries_user_id ON ai_summaries(user_id);

CREATE TABLE ai_explanations (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    annotation_id   UUID NOT NULL REFERENCES annotations(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    model_used      VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_explanations_annotation_id ON ai_explanations(annotation_id);

CREATE TABLE ai_quizzes (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    scope           VARCHAR(20) NOT NULL
                    CHECK (scope IN ('PAGE', 'SECTION', 'CHAPTER', 'BOOK')),
    scope_ref_id    UUID,
    questions       JSONB NOT NULL,   -- [{question, options[], correct_index, explanation}]
    model_used      VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_quizzes_document_id ON ai_quizzes(document_id);
CREATE INDEX idx_ai_quizzes_user_id ON ai_quizzes(user_id);

CREATE TABLE ai_flashcards (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_id     UUID REFERENCES documents(id) ON DELETE CASCADE,
    annotation_id   UUID REFERENCES annotations(id) ON DELETE CASCADE,
    source_type     VARCHAR(20) NOT NULL
                    CHECK (source_type IN ('HIGHLIGHT', 'NOTE', 'CHAPTER', 'BOOK')),
    front_text      TEXT NOT NULL,
    back_text       TEXT NOT NULL,
    model_used      VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_flashcards_user_id ON ai_flashcards(user_id);
CREATE INDEX idx_ai_flashcards_document_id ON ai_flashcards(document_id);

-- Moderation is polymorphic across content types; content_id references the
-- source row (blogs.id / blog_comments.id / annotations.id / ai_chat_messages.id)
-- without an FK, since it spans multiple tables. Enforce integrity in the
-- application/service layer.
CREATE TABLE ai_moderation_logs (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    content_type        VARCHAR(20) NOT NULL
                        CHECK (content_type IN ('BLOG', 'COMMENT', 'NOTE', 'CHAT')),
    content_id          UUID NOT NULL,
    content_snapshot    TEXT NOT NULL,
    verdict             VARCHAR(20) NOT NULL CHECK (verdict IN ('SAFE', 'UNSAFE')),
    reason              TEXT,
    model_used          VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_moderation_logs_content ON ai_moderation_logs(content_type, content_id);
CREATE INDEX idx_ai_moderation_logs_verdict ON ai_moderation_logs(verdict) WHERE verdict = 'UNSAFE';

COMMIT;

-- ============================================================================
-- 10. SEED DATA — default subscription plans
-- ============================================================================
INSERT INTO subscription_plans (code, name, price_cents, currency, billing_interval, features)
VALUES
    ('FREE', 'Free', 0, 'USD', 'LIFETIME',
     '{"read_books": true, "basic_library": true, "basic_highlight": true, "basic_notes": true}'::jsonb),
    ('PRO', 'Pro', 999, 'USD', 'MONTHLY',
     '{"unlimited_annotations": true, "ai_explain": true, "ai_chat": true,
       "ai_summary": true, "ai_quiz": true, "ai_flashcards": true,
       "advanced_stats": true}'::jsonb)
ON CONFLICT (code) DO NOTHING;